spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration,org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  data:
    cassandra:
      cluster: cassandra
      keyspace-name: store
      port: 9042
      contact-points: localhost
      schema-action: create_if_not_exists
      local-datacenter: datacenter1

server:
  port: 8080
